// Generated by LiveScript 1.2.0
(function(){
  var mod;
  mod = angular.module('caasi', ['caasi.services']).directive('lyDiff', function(model){
    return {
      restrict: 'A',
      scope: true,
      templateUrl: './tpl.html'
    };
  });
}).call(this);
