// Generated by LiveScript 1.2.0
(function(){
  this.BillsCtrl = function($scope, model){
    $scope.bills = ['989L16035', '970L19045', '1619L16058'];
    return $scope.get = function(bill){
      return model.get("bills/" + bill + "/data").success(function(data){
        var contents, i$, len$, content, results$ = [];
        console.log(data);
        contents = data.content[0].content;
        for (i$ = 0, len$ = contents.length; i$ < len$; ++i$) {
          content = contents[i$];
          results$.push(console.log(model.parse(content[0])));
        }
        return results$;
      });
    };
  };
}).call(this);
