// Generated by LiveScript 1.2.0
(function(){
  var base, slice$ = [].slice, replace$ = ''.replace;
  base = "http://api.ly.g0v.tw/v0/collections/";
  angular.module('caasi.services', []).factory('model', ['$q', '$http'].concat(function($q, $http){
    return {
      get: function(it){
        return $http({
          method: 'GET',
          cache: true,
          url: base + it
        });
      },
      parseHeading: function(heading){
        var ref$, _, _items, zhutil;
        if ((ref$ = heading.match(/第(.+)條(?:之(.+))?/)) != null) {
          _ = ref$[0], _items = slice$.call(ref$, 1);
        }
        if (!_items) {
          return heading;
        }
        zhutil = require('zhutil');
        return _items.filter(function(it){
          return it;
        }).map(zhutil.parseZHNumber).join('-');
      },
      parse: function(article){
        return {
          text: replace$.call(article, /^第(.*?)(條(之.*?)?|章|篇|節)\s+/, ''),
          heading: this.parseHeading(replace$.call(RegExp.lastMatch, /\s+$/, ''))
        };
      }
    };
  }));
}).call(this);
