// Generated by LiveScript 1.2.0
(function(){
  var base;
  base = "http://api.ly.g0v.tw/v0/collections/";
  angular.module('caasi.services', []).factory('model', ['$q', '$http'].concat(function($q, $http){
    return {
      get: function(it){
        return $http({
          method: 'GET',
          cache: true,
          url: base + it
        });
      }
    };
  }));
}).call(this);
