// Generated by LiveScript 1.2.0
(function(){
  zhStrokeData.loaders.JSON('/json/840c.json').then(function(it){
    var strokes, res$, i$, len$, data, moe, canvas, angle, update;
    res$ = [];
    for (i$ = 0, len$ = it.length; i$ < len$; ++i$) {
      data = it[i$];
      res$.push(new zhStrokeData.Stroke(data));
    }
    strokes = res$;
    moe = new zhStrokeData.Comp(strokes);
    canvas = document.getElementById('mark-two');
    moe.scaleX = moe.scaleY = 0.2;
    angle = 1.5;
    update = function(){
      moe.time = (1 - Math.sin(angle)) / 2;
      canvas.width = canvas.width;
      moe.render(canvas);
      angle = angle + 0.01;
      return requestAnimationFrame(update);
    };
    return requestAnimationFrame(update);
  });
}).call(this);
