// Generated by LiveScript 1.2.0
(function(){
  angular.module('caasi', []).directive('lyDiff', function(){
    return {
      restrict: 'A',
      scope: true,
      templateUrl: './diff.html'
    };
  });
}).call(this);
