// Generated by LiveScript 1.2.0
(function(){
  var x$, stats, y$, renderer, z$, stage, texture, mine, z1$, z2$, z3$, gameLoop;
  x$ = (stats = new Stats).domElement.style;
  x$.position = 'absolute';
  x$.left = '0';
  x$.top = '0';
  y$ = (renderer = PIXI.autoDetectRenderer(400, 300)).view.style;
  y$.position = 'absolute';
  y$.margin = 'auto';
  y$.left = '0';
  y$.top = '0';
  y$.right = '0';
  y$.bottom = '0';
  z$ = document.body;
  z$.appendChild(renderer.view);
  z$.appendChild(stats.domElement);
  stage = new PIXI.Stage(0x16161D);
  texture = PIXI.Texture.fromImage('./img/mine.png');
  mine = new PIXI.Sprite(texture);
  z1$ = mine;
  z2$ = z1$.position;
  z2$.x = 200;
  z2$.y = 150;
  z3$ = z1$.anchor;
  z3$.x = 0.5;
  z3$.y = 0.5;
  stage.addChild(mine);
  gameLoop = function(){
    stats.begin();
    mine.rotation += 5 * Math.PI / 360;
    renderer.render(stage);
    requestAnimationFrame(gameLoop);
    return stats.end();
  };
  requestAnimationFrame(gameLoop);
}).call(this);
