// Generated by LiveScript 1.2.0
(function(){
  angular.module('caasi', []).directive('scrollSpy', ['$window'].concat(function($window){
    return {
      restrict: 'A',
      transclude: true,
      replace: true,
      templateUrl: './tpl.html',
      controller: function($scope){
        var p;
        $window.onscroll = function(arg$){
          var pageY, t, i;
          pageY = arg$.pageY;
          for (i in $scope.targets) {
            t = $scope.targets[i];
            if (t.top <= pageY && pageY < t.bottom) {
              break;
            }
            t = null;
          }
          if (p !== t) {
            $scope.$apply(function(){
              if (p != null) {
                p.highlight = false;
              }
              return t != null ? t.highlight = true : void 8;
            });
          }
          return p = t;
        };
        $scope.targets = [];
        return $scope.$on('spy:register', function(e, target){
          return $scope.targets.push(target);
        });
      }
    };
  })).directive('spy', ['$timeout'].concat(function($timeout){
    return {
      restrict: 'A',
      link: function($scope, elem, attrs){
        var top;
        elem.attr('id', $scope.$index);
        top = elem.parent().position().top;
        return $timeout(function(){
          return $scope.$emit('spy:register', {
            index: $scope.$index,
            heading: elem.text(),
            top: top,
            bottom: top + elem.parent().height()
          });
        });
      }
    };
  }));
}).call(this);
