// Generated by LiveScript 1.2.0
(function(){
  angular.module('caasi', []).directive('scrollSpy', [].concat(function($scope){
    return {
      restrict: 'A',
      transclude: true,
      replace: true,
      templateUrl: './tpl.html',
      controller: function($scope){
        $scope.targets = [];
        return $scope.$on('spy:register', function(e, target){
          return $scope.targets.push(target);
        });
      }
    };
  })).directive('spy', ['$timeout'].concat(function($timeout){
    return {
      restrict: 'A',
      link: function($scope, elem, attrs){
        elem.attr('id', $scope.$index);
        return $timeout(function(){
          return $scope.$emit('spy:register', {
            index: $scope.$index,
            heading: elem.text()
          });
        });
      }
    };
  }));
}).call(this);
