// Generated by LiveScript 1.2.0
(function(){
  this.SpyCtrl = function($scope){
    var i;
    return $scope.articles = (function(){
      var i$, results$ = [];
      for (i$ = 0; i$ < 30; ++i$) {
        i = i$;
        results$.push({
          heading: Math.random() + "",
          content: '家庭生活費用除法律或契約另有約定外，由夫妻各依其經濟能力、家事勞動或其他情事分擔之。'
        });
      }
      return results$;
    }());
  };
}).call(this);
